[project]
name = "play-with-pydantic-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "notebook>=7.4.5",
    "pydantic-ai[examples]>=0.8.1",
    "python-dotenv>=1.1.1",
]
